### ISSUE TITLE
日志配置

### ISSUE THREAD

**Issue by vernvern** [vernvern/thtr#2]
需求：

- 使用logging模块
- 将日志记录到容器里面的  /opt/log/python目录下，分stdout和stderr两个日志文件
- local环境下，将debug模式的日志输出到console，使用`docker logs  thtr_python`命令能够看到
- production环境下，将info或以上级别的日志输出到console，使用`docker logs  thtr_python`命令能够看到
- 编码规范符合pep8
- 新开分支命名和issue编号一样～像这条就用 `2`

**Comment by oujin4211** [comment]
- [ ]

**Comment by oujin4211** [comment]
> 需求：
> 
> 

- [x] 使用logging模块
- [x] 将日志记录到容器里面的  /opt/log/python目录下，分stdout和stderr两个日志文件
- [x] local环境下，将debug模式的日志输出到console，使用`docker logs thtr_python`命令能够看到
- [x] production环境下，将info或以上级别的日志输出到console，使用`docker logs thtr_python`命令能够看到
- [x] 编码规范符合pep8
- [x] 新开分支命名和issue编号一样～像这条就用 `2`
